# example 1: on push to master
name: Bump version
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: commit messages
      env:
        COMMIT_MESSAGES: ${{  contains(toJson(github.event.commits.*.message), '#nextversion') }}
      run: echo "$COMMIT_MESSAGES"
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
      if: ${{ env.COMMIT_MESSAGES == 'true' }}
      run: echo 'this step is executed'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: false